#!/bin/sh
#killall hostapd
#killall wpa_supplicant
#killall dnsmasq
#killall dhcpcd

NAME1=wpa_supplicant
DAEMON1=/usr/sbin/$NAME1
PIDFILE1=/var/run/$NAME1.pid

NAME2=hostapd
DAEMON2=/usr/sbin/$NAME2
PIDFILE2=/var/run/$NAME2.pid

NAME3=dnsmasq
DAEMON3=/usr/sbin/$NAME3
PIDFILE3=/var/run/$NAME3.pid

NAME4=dhcpcd
DAEMON4=/usr/sbin/$NAME4
PIDFILE4=/var/run/${NAME4}-wlan0.pid

ap_name_file=/etc/wifi/ap_name
if [ -f $ap_name_file ];then
    ap_name=`cat /etc/wifi/ap_name`
else
    < /dev/urandom tr -dc A-Za-z | head -c 8 | cat > /etc/wifi/ap_name
    ap_name=`cat /etc/wifi/ap_name`
fi

ssid=amlogic-audio-$ap_name
password=12345678

echo 0 > /etc/hostapd_temp.conf
echo "interface=wlan1
driver=nl80211
ctrl_interface=/var/run/hostapd
ssid=${ssid}
channel=6
ieee80211n=1
hw_mode=g
ignore_broadcast_ssid=0"  > /etc/hostapd_temp.conf

echo "
wpa=3
wpa_passphrase=${password}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP" >> /etc/hostapd_temp.conf

MULTI_WIFI=/usr/bin/multi_wifi_load_driver


case "$1" in
    start)
	    skt_board=`cat /proc/device-tree/amlogic-dt-id`
	    case ${skt_board} in
			"axg_a113d_skt_v1")
				exit 0
				;;
			"axg_a113x_skt_v1")
				exit 0
				;;
	    esac

        killall hostapd
        killall wpa_supplicant
        killall dnsmasq
		echo "start wifi station mode load driver and setup......"
		$MULTI_WIFI station 1

		ifconfig wlan0 up > /dev/null
		sleep 2
		if [ $? -eq 0 ]; then
#			dhd_priv iapsta_init mode gosta
#			sleep 1
#			ifconfig wlan1 192.168.2.1
#			start-stop-daemon -S -m -p $PIDFILE3  -x $DAEMON3  -- -iwlan1  --dhcp-option=3,192.168.2.1 --dhcp-range=192.168.2.50,192.168.2.200,12h -p100
			sleep 1
		fi
		ifconfig wlan0 &> /dev/null
		start-stop-daemon -S -m -p $PIDFILE1 -b -x $DAEMON1 -- -Dnl80211 -iwlan0 -c/vendor/wpa_supplicant.conf
		sleep 1
		ifconfig wlan0 &> /dev/null

                dhcpcd wlan0 -t0 &
        ;;
    stop)
        killall hostapd
        killall wpa_supplicant
        killall dnsmasq
        killall dhcpcd
        echo -n "Stopping supplicant..."
        start-stop-daemon -K -o -p $PIDFILE1
        start-stop-daemon -K -o -p $PIDFILE3
        sleep 2
        rm -f $PIDFILE1
        rm -f $PIDFILE3
	$MULTI_WIFI station 0
        $POWERCTL 0
        ;;
    netready|netup|netdown|netchange) ;;
    restart|reload)
        killall hostapd
        killall wpa_supplicant
        killall dnsmasq
        start-stop-daemon -K -s HUP -n wpa_supplicant
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

